//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNinja.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GROCERY_DB_Entities : DbContext
    {
        public GROCERY_DB_Entities()
            : base("name=GROCERY_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USERS> USERS { get; set; }
    
        public virtual int SP_USERS_LOGIN(string uSUARIO, string pASS, ObjectParameter userId, ObjectParameter user)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_USERS_LOGIN", uSUARIOParameter, pASSParameter, userId, user);
        }
    
        public virtual ObjectResult<SP_USERS_QUERY_Result> SP_USERS_QUERY(Nullable<int> insertedById)
        {
            var insertedByIdParameter = insertedById.HasValue ?
                new ObjectParameter("InsertedById", insertedById) :
                new ObjectParameter("InsertedById", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_USERS_QUERY_Result>("SP_USERS_QUERY", insertedByIdParameter);
        }
    }
}
