//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNinja.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int RowId { get; set; }
        public int InsertedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedById { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Modified { get; set; }
        public int EnabledSystem { get; set; }
        public string USUARIO { get; set; }
        public byte[] PASS { get; set; }
        public System.Guid SALT { get; set; }
        public int ID_NIVEL { get; set; }
        public int ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string ESTADO { get; set; }
        public string TELEFONO { get; set; }
        public string FOTO { get; set; }
    }
}
